=== doudouchat/exemple-service/exemple-service-api-integration/src/test/resources/account.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"additionalProperties": false,
	"required": [
		"email",
		"lastname",
		"firstname",
		"birthday"
	],
	"dependencies": {
		"optin_mobile": {
			"if": {
				"properties": {
					"optin_mobile": {
						"const": true
					}
				}
			},
			"then": {
				"required": [
					"mobile"
				]
			}
		}
	},
	"properties": {
		"id": {
			"type": "number",
			"readOnly": true
		},
		"email": {
			"type": "string",
			"format": "email",
			"login": true
		},
		"civility": {
			"type": "string",
			"enum": [
				"Mr",
				"Mme"
			]
		},
		"lastname": {
			"type": "string",
			"pattern": "^(?!\\s*$).+"
		},
		"firstname": {
			"type": "string",
			"pattern": "^(?!\\s*$).+"
		},
		"birthday": {
			"type": "string",
			"format": "date"
		},
		"creation_date": {
			"type": "string",
			"format": "date-time",
			"writeOnly": true
		},
		"optin_mobile": {
			"type": "boolean"
		},
		"mobile": {
			"type": "string"
		},
		"addresses": {
			"type": "object",
			"maxProperties": 2,
			"additionalProperties": {
				"$ref": "#/definitions/Address"
			}
		},
		"cgus": {
			"type": "array",
			"uniqueItems": true,
			"maxItems": 2,
			"items": {
				"$ref": "#/definitions/Cgu"
			}
		}
	},
	"definitions": {
		"Address": {
			"type": "object",
			"properties": {
				"street": {
					"type": "string",
					"pattern": "^(?!\\s*$).+"
				},
				"city": {
					"type": "string",
					"pattern": "^(?!\\s*$).+"
				}
			},
			"required": [
				"street",
				"city"
			]
		},
		"Cgu": {
			"type": "object",
			"properties": {
				"code": {
					"type": "string",
					"pattern": "^(?!\\s*$).+"
				},
				"version": {
					"type": "string",
					"pattern": "^(?!\\s*$).+"
				}
			},
			"required": [
				"code",
				"version"
			]
		}
	}
}

=== doudouchat/exemple-service/exemple-service-launcher/src/test/resources/account/nominal_account.json
{
	"optin_mobile": true,
	"birthday": "1967-06-15",
	"firstname": "Jean",
	"addresses": {
		"job": {
			"city": "Paris",
			"street": "rue de la paix"
		},
		"home": {
			"city": "Lyon",
			"street": "rue de la poste"
		}
	},
	"civility": "Mr",
	"mobile": "0610203040",
	"cgus": [
		{
			"code": "code_1",
			"version": "v0"
		}
	],
	"email": "963508ad-470e-4cf8-9576-cfae70ad9a1e@gmail.com",
	"lastname": "Dupont"
}
